
import type { Metadata } from "next";
import { Inter, Poppins, Roboto } from "next/font/google";
import "./globals.css";
import { Provider } from "@/data/context/Providers/providers";




const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({weight:['100','200', '300', '400', '500', '600', '700', '800', '900'], subsets: ["latin"] });
const roboto = Roboto({weight:["100","300","400","500","700","900"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Provider>
          {children}

        </Provider>
        </body>
    </html>
  );
}
